name: Create Release
run-name: Create Release for ${{ github.ref_name }}

on:
  push:
    tags:
      - v*.*.*

jobs:
  create_release:
    name: Release Action to GitHub

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: "./"
